import { Router, Request, Response } from 'express';
import { requireAuth } from '../middleware/auth.js';
import prisma from '../utils/prisma.js';
import { successResponse, errorResponse } from '../utils/responseEnvelope.js';

const router = Router();

// GET /api/forecasts/mine
router.get('/mine', requireAuth, async (req: Request, res: Response) => {
  try {
    const dbUser = await prisma.users.findUnique({
      where: { firebase_uid: req.firebaseUser!.uid },
    });
    
    if (!dbUser || dbUser.role !== 'buyer') {
      res.status(403).json(errorResponse('FORBIDDEN', 'Only buyers can fetch forecasts'));
      return;
    }
    
    const forecasts = await prisma.forecasts.findMany({
      where: { buyer_id: dbUser.id },
      orderBy: { created_at: 'desc' },
    });
    
    res.json(successResponse(forecasts));
  } catch (error) {
    res.status(500).json(errorResponse('INTERNAL_SERVER_ERROR', 'Failed to fetch forecasts'));
  }
});

// POST /api/forecasts/run (Internal AI Agent endpoint)
router.post('/run', async (req: Request, res: Response): Promise<void> => {
  try {
    const { buyer_id } = req.body;
    
    if (!buyer_id) {
      res.status(400).json(errorResponse('INVALID_INPUT', 'Missing buyer_id'));
      return;
    }
    
    // In a real app, this would trigger the AI agent logic to generate forecasts
    // For now, we simulate generating a forecast
    
    const forecast = await prisma.forecasts.create({
      data: {
        buyer_id,
        material_name: 'Simulated Material',
        predicted_qty: 500,
        predicted_need_date: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000), // 14 days
        confidence: 0.85,
        reasoning: 'Generated by mock forecast recompute.',
      }
    });
    
    res.status(201).json(successResponse(forecast));
  } catch (error) {
    res.status(500).json(errorResponse('INTERNAL_SERVER_ERROR', 'Failed to run forecast'));
  }
});

export default router;
