import { GoogleGenerativeAI } from '@google/generative-ai';
import * as dotenv from 'dotenv';

dotenv.config();

const apiKey = process.env.GEMINI_API_KEY || '';
const defaultModelName = process.env.GEMINI_MODEL || 'gemini-2.0-flash';
const embeddingModelName = 'text-embedding-004';

let genAI: GoogleGenerativeAI | null = null;

if (apiKey && apiKey !== 'mock_key') {
  genAI = new GoogleGenerativeAI(apiKey);
} else {
  console.warn('Warning: GEMINI_API_KEY is not set or is using a mock key. Gemini calls will run in mock mode.');
}

/**
 * Exponential backoff helper for retrying transient API errors.
 */
async function retryWithBackoff<T>(fn: () => Promise<T>, retries = 2, delay = 1000): Promise<T> {
  try {
    return await fn();
  } catch (error: any) {
    if (retries <= 0) {
      throw error;
    }
    console.warn(`Gemini API call failed (retries left: ${retries}). Retrying in ${delay}ms... Error:`, error?.message || error);
    await new Promise((resolve) => setTimeout(resolve, delay));
    return retryWithBackoff(fn, retries - 1, delay * 2);
  }
}

/**
 * Clean and parse JSON responses from Gemini defensively.
 * Handles removing markdown fences if they are generated by the model.
 */
export function cleanAndParseJson<T>(rawText: string, fallback: T): T {
  try {
    // Strip markdown JSON code fences if present
    let cleanText = rawText.trim();
    if (cleanText.startsWith('```')) {
      // Find start of JSON content
      const jsonStart = cleanText.indexOf('{');
      const jsonEnd = cleanText.lastIndexOf('}');
      if (jsonStart !== -1 && jsonEnd !== -1 && jsonEnd > jsonStart) {
        cleanText = cleanText.substring(jsonStart, jsonEnd + 1);
      } else {
        // If there's no brackets, try stripping ```json and ```
        cleanText = cleanText.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '');
      }
    }

    return JSON.parse(cleanText) as T;
  } catch (error) {
    console.error('Failed to parse JSON response from Gemini. Raw text:', rawText, 'Error:', error);
    return fallback;
  }
}

/**
 * Calls Gemini text generation API.
 */
export async function askGemini(prompt: string, opts?: { model?: string }): Promise<string> {
  // If running in test mode or without a real API key, return mock responses
  if (!genAI || process.env.NODE_ENV === 'test') {
    const promptLower = prompt.toLowerCase();
    if (promptLower.includes('forecasting assistant')) {
      return JSON.stringify({
        predicted_qty: 120,
        predicted_need_in_days: 14,
        confidence: 0.85,
        reasoning: 'Gemini reasoning: constant order frequency.'
      });
    }
    if (promptLower.includes('trust and verification')) {
      return 'Score rose due to on-time deliveries.';
    }
    if (promptLower.includes('dynamic pricing')) {
      return JSON.stringify({
        fair_price_min: 15,
        fair_price_max: 25,
        reasoning: 'Gemini estimated fair price band.'
      });
    }
    return 'Mock Gemini text response';
  }

  const modelName = opts?.model || defaultModelName;
  const model = genAI.getGenerativeModel({ model: modelName });

  return retryWithBackoff(async () => {
    const result = await model.generateContent(prompt);
    const response = await result.response;
    return response.text();
  });
}

/**
 * Generates vector embedding for the given text (768 dimensions using text-embedding-004).
 */
export async function generateEmbedding(text: string): Promise<number[]> {
  if (!genAI || process.env.NODE_ENV === 'test') {
    // Return mock embedding of 768 dimensions
    return Array.from({ length: 768 }, () => 0.1);
  }

  const model = genAI.getGenerativeModel({ model: embeddingModelName });

  return retryWithBackoff(async () => {
    const result = await model.embedContent(text);
    if (!result.embedding || !result.embedding.values) {
      throw new Error('No embedding values returned from Gemini API.');
    }
    return result.embedding.values;
  });
}
